services:
  - type: web
    name: movie-booking-api
    runtime: node
    env: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health
